### PR TITLE
Delete obsolete AWS files

### PR DESCRIPTION
**Pull request by jdmooney**
awf-cf.adoc replaced how-to-set-up-a-cloud-formation-system.adoc/how-to-maintain-a-cloud-formation-system.adoc
aws-multitier.adoc replaced by how-to-set-up-a-multi-tier-system.adoc/how-to-maintain-a-multi-tier-system.adoc
aws-singletier.adoc replaced by how-to-set-up-a-single-tier-system.adoc/how-to-maintain-a-single-tier-system.adoc
aws-single-ami.adoc obsolete. No need to replace.

### CODE REVIEW

**Review by reshmabidikar — COMMENTED** [review]
Looks good, just one minor comment: Doesn't `aws-tools.adoc` need to be deleted as done in the [earlier PR](https://github.com/killbill/killbill-docs/pull/554)?

**Comment by vnandwana** [comment]
The `aws-cf.doc` has info about [updating stack](https://github.com/killbill/killbill-docs/blob/v3/userguide/tutorials/aws-cf.adoc#update-configuration), this is missing in the replaced doc. Could you please take a look? Thank you.

**Comment by jdmooney** [comment]
@vnandwana could you be more specific? I don't think I am finding the content you are referring to.

**Comment by vnandwana** [comment]
@jdmooney,  sure, `aws-cf.adoc` has information about updating a CloudFormation stack (see [https://github.com/killbill/killbill-docs/blob/v3/userguide/tutorials/aws-cf.adoc#update-configuration](https://github.com/killbill/killbill-docs/blob/v3/userguide/tutorials/aws-cf.adoc#update-configuration)). 

This information is missing in the docs that has replaced the `aws-cf.adoc`. We need to add a section in the how-to-set-up-a-cloud-formation-system.adoc/how-to-maintain-a-cloud-formation-system.adoc about updating the configuration.

**Comment by reshmabidikar** [comment]
https://github.com/killbill/killbill-docs/pull/580 supersedes the work in this PR, so closing this PR.

**Pull request closed without merging**
