### PR TITLE
Documentation changes

### PR DESCRIPTION
**Pull request by reshmabidikar**
Includes the following:

- Added the `org.killbill.invoice.usage.missing.lenient` and `org.killbill.jaxrs.get.ro` properties to the [config ](https://docs.killbill.io/latest/userguide_configuration.html)doc
- Added additional notes about `kpm diagnostic` to [debugging](https://docs.killbill.io/latest/debugging.html#_seeking_help) doc
- Split [Getting started](https://docs.killbill.io/latest/getting_started.html) doc into separate files and reorganized headings slightly
- Modified [Getting started](https://docs.killbill.io/latest/getting_started.html) doc to add a note about the `kaui.url` property
- Minor corrections to [overdue ](https://docs.killbill.io/latest/overdue.html)and [stripe ](https://docs.killbill.io/latest/stripe_plugin.html) docs

### CODE REVIEW

**Review by pierre — APPROVED** [review]

**Review by sbrossie — COMMENTED** [review]
👍

**Comment by ghost** [comment]
Reshma, here are a few things:

1. Confused because the statements seem to contradict one another. And why show them the first two commands if you don't use them?
image

2. In the next release of KB, we're moving to Java 11 - 17. Should this be changed or some other note added?
image

3. If this was intended to be in code, the URL needs the closing single quote.
image

4. For some reason, some of the links in this section are not displaying properly, though they do render correctly.
image

5. Wasn't sure "file file" was correct.
image

**Comment by reshmabidikar** [comment]
Hi Mary, thanks for pointing out all these issues. Please see my comments below:

1. I am not familiar with Mac/Ubuntu, so I just copied the existing instructions as they were, but what you are saying makes sense to me. @pierre,@sbrossie, any objection if I delete the section that starts with `We have not installed Docker Compose in these commands...`?
2. Yup I agree, this is something I've been meaning to ask about as well. @pierre,@sbrossie, could you confirm the Java version that we would be moving to? I will first test the Tomcat installation part on my local machine with the new Java version and if all works well, I will update the docs accordingly
3. No, this was not intended as code, the backslash is intentional. When localhost URLs like this are added to the docs, they should be escaped like this, otherwise, it causes SEO issues
4. I think this is an issue with all our docs. I will try to fix this by specifying the link text in the cross-reference.  
5. You are right, I'll fix this. 

I will be creating a PR soon with some other changes, I will include 4 and 5 as part of that PR.

**Comment by pierre** [comment]
For 1., the first set of instructions is for `Docker`, the second for `Docker Compose` (two different pieces of software, with two different install methods).

For 2., Java 8 for 0.22, Java 11 for 0.24. You can see that we actually have docs for all versions of Kill Bill:

* https://github.com/killbill/killbill-docs/tree/gh-pages
* For 0.20 for instance: https://docs.killbill.io/0.20/getting_started.html

Once 0.24 is released, we would keep these instructions as-is for the 0.22 pages and update the `latest` pages.

**Pull request merged**
