### PR TITLE
added account export option to aws KPM diagnostic

### PR DESCRIPTION
**Pull request by KBbitsP**
Hi @reshmabidikar

### CODE REVIEW

**Review by reshmabidikar — APPROVED** [review]
Looks good.

**Comment by reshmabidikar** [comment]
@FlowWriter, I know you and Jim are working on some AWS doc reorganization. Could you please take a look at this PR and check if it is good to merge?

**Comment by ghost** [comment]
@reshmabidikar and @KBbitsP - Yes, @jdmooney needs to know about this change so he can add it to his works-in-progress.

**Comment by jdmooney** [comment]
@reshmabidikar @FlowWriter thanks. I'm still considering how to handle the diagnostic and maintenance information. I will be sure to include this new parameter.

**Comment by reshmabidikar** [comment]
Thanks, @jdmooney. So are we good to close this PR?

**Comment by reshmabidikar** [comment]
Closing this PR as Jim would be incorporating this change as part of his work.

**Pull request closed without merging**
